---
name: checks

"on": pull_request

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "docker run --rm -v ${{ github.workspace }}:/root puppet/pdk:3.0.1.3 validate"
      - run: "docker run --rm -v ${{ github.workspace }}:/root puppet/pdk:3.0.1.3 test unit"
