---
name: publish

"on":
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish a tagged version to the Puppet Forge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to the Puppet Forge
        run: >
          docker run --rm
          -v ${{ github.workspace }}:/root
          puppet/pdk:3.0.1.3
          release --force --skip-changelog --skip-documentation --skip-dependency --skip-validation --forge-token=${{ secrets.forge_token }}
