---
name: release

"on":
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release a tagged version to GitHub Releases
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1.14.0
        with:
          makeLatest: true
